@baseUrl = http://127.0.0.1:3000
@authToken = {{authenticate.response.body.accessToken}}
# USERS

@baseUrl = http://127.0.0.1:3000

# @name authenticate
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "email": "johndoe3@example.com",
  "password": "password123"
}

# Cria um novo usuário com os dados fornecidos no corpo da requisição.
###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "johndoe2",
  "email": "johndoe43@example.com",
  "password": "password123"
}

# Obtém uma lista de todos os usuários.
###
GET {{baseUrl}}/users?limit=10&offset=0&sort=desc
Authorization: Bearer {{authToken}}

# Obtém os detalhes de um usuário específico com o ID fornecido.
###
GET {{baseUrl}}/users/062e911e-32d2-4d31-b97e-a21109a7a91d
Authorization: Bearer {{authToken}}
Content-Type: application/json

# Atualiza um usuário específico com o ID fornecido.
###
PATCH {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "newName"
}

# Atualiza a senha de um usuário específico.
###
PATCH {{baseUrl}}/users/new-password/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "password": "password"
}

# Exclui um usuário específico com o ID fornecido.
###
DELETE {{baseUrl}}/users/062e911e-32d2-4d31-b97e-a21109a7a91d
Authorization: Bearer {{authToken}}
