@baseUrl = http://127.0.0.1:3000

# USERS

# Cria um novo usuário com os dados fornecidos no corpo da requisição.
###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "johndoe",
  "email": "johndoe3@example.com",
  "password": "password123"
}

# Obtém uma lista de todos os usuários.
###
GET {{baseUrl}}/users/
?limit=10
&offset=0
&sort=desc

# Obtém os detalhes de um usuário específico com o ID 1.
###
GET {{baseUrl}}/users/7ac111ca-d51c-4a1c-a73e-886ac4e0bb8e

# Atualiza um usuário específico com o ID 1 usando os dados fornecidos no corpo da requisição.
###
PATCH {{baseUrl}}/users/7ac111ca-d51c-4a1c-a73e-886ac4e0bb8e
Content-Type: application/json

{
  "name": "newName",
}

# Exclui um usuário específico com o ID 1.
###
DELETE {{baseUrl}}/users/7ac111ca-d51c-4a1c-a73e-886ac4e0bb8e
