@baseUrl = http://127.0.0.1:3000
@authToken = {{authenticate.response.body.accessToken}}
# @name authenticate
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "email": "johndoe3@example.com",
  "password": "password123"
}
